"""empty message

Revision ID: 34beb1c91618
Revises: 00f321bf6225
Create Date: 2021-08-21 18:12:11.362282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34beb1c91618'
down_revision = '00f321bf6225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
