"""empty message

Revision ID: 643eaf17bd39
Revises: acf3a4f14578
Create Date: 2021-08-21 18:22:55.556771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643eaf17bd39'
down_revision = 'acf3a4f14578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
